# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6692a7e506d6ab5dc00d6f8051851a2df7dc9452e2fa4b447d4e7e357bf34adfe9a7107d4e3d71a5283e977aeccbd7f4ff560e188176c04cccc042eaade83e12

test:
  secret_key_base: becf561e05663cdf3ec790a96a259b0ab1e68185482c59cce033bbae17a835bfd9f4abbbd80d5e9a557e35a8dd2191b6dbb3828d2dd1e41c736ba75b4d626bea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  jwt_secret: <%= ENV["TOKEN_SECRET"] %>
  jwt_algorithm: HS512
  slack: <%= ENV["SLACK"] %>
