# Seed Category
level_0 = Category.create(name: 'Fashion & Accessories')

level_1 = Category.create(name: 'Women', parent_id: level_0.id.to_s)
level_2 = Category.create(name: 'Active Yoga & Outdoor', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Dresses', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Tops & Tees', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Sweaters', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Jackets', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Coats', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Shorts', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Skirts', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Jeans', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Pants', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Swimsuits & Cover-Ups', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Sleep Lounge & Robes', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Bras Panties & Lingerie', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Hosiery Leggings & Socks', parent_id: level_1.id.to_s)

level_1 = Category.create(name: 'Men', parent_id: level_0.id.to_s)
level_2 = Category.create(name: 'Active & Outdoor', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Dress Shirts', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Tops & Tshirts', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Casual Shirts & Polos', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Sweaters & Sweatshirts', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Coats & Jackets', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Shorts', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Jeans', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Pants', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Swimwear', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Formal Wear', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Lounge & Sleepwear', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Underwear', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Socks', parent_id: level_1.id.to_s)

level_1 = Category.create(name: 'Men\'s Shoes', parent_id: level_0.id.to_s)
level_2 = Category.create(name: 'Athletic', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Boots', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Sneakers', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Loafers & Slip-Ons', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Sandals & Flip-Flops', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Slippers', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Dress Shoes', parent_id: level_1.id.to_s)

level_1 = Category.create(name: 'Women\'s Shoes', parent_id: level_0.id.to_s)
level_2 = Category.create(name: 'Athletic & Outdoor', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Boots & Booties', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Clogs & Mules', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Sneakers', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Flats', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Slippers', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Wedges', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Evening & Pumps', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Sandals', parent_id: level_1.id.to_s)

level_1 = Category.create(name: 'Bags', parent_id: level_0.id.to_s)
level_2 = Category.create(name: 'Baguettes', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Clutch', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Cosmetic Bag', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Handbags', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Hobo', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Sling Bag', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Backpack', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Satchels', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Shoulder Bag', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Tote & Shopper Bag', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Suitcase & Travel bag', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Vintage', parent_id: level_1.id.to_s)

level_1 = Category.create(name: 'Jewelry', parent_id: level_0.id.to_s)
level_2 = Category.create(name: 'Earrings', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Gemstones', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Bross', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Ring', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Bracelets & Bangles', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Necklace', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Pendant', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Pin', parent_id: level_1.id.to_s)

level_1 = Category.create(name: 'Watch', parent_id: level_0.id.to_s)
level_2 = Category.create(name: 'Analog', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'Digital', parent_id: level_1.id.to_s)
level_2 = Category.create(name: 'LED', parent_id: level_1.id.to_s)
